scripts: jenkin: check for board name and device part number is in sync
jenkin will compile testapp only when board name belongs to configured device
part number

Signed-off-by: Raj Ranjan <raj.ranjan@alifsemi.com>

diff --git a/scripts/github/jenkins/Jenkinsfile b/scripts/github/jenkins/Jenkinsfile
--- a/scripts/github/jenkins/Jenkinsfile
+++ b/scripts/github/jenkins/Jenkinsfile
@@ -225,6 +225,7 @@ pipeline {
                         CURR_OS=("NONE")
                         CURR_COMPILER=("armclang" "gcc")
                         CURR_DEV=("AE722F80F55D5" "AE1C1F4051920" "AE822FA0E5597")
+                        CURR_BOARDS=("DevKit-e7" "DevKit-e1c" "DevKit-e8")
                         CURR_RTSS=("HE" "HP")
                         CURR_BOOT=("TCM" "MRAM")
 
@@ -236,33 +237,42 @@ pipeline {
                                 do
                                     for devName in ${!CURR_DEV[@]}
                                     do
-                                        for osName in ${!CURR_OS[@]}
+                                        for brdName in ${!CURR_BOARDS[@]}
                                         do
-                                            echo "===================================================================================="
-                                            if [ -d build ]; then
-                                                echo -e "Deleting Build directory..."
-                                                rm -rf build
+                                            devShortName="${CURR_BOARDS[brdName]#*-}"
+                                            alifDevShortName="A$(echo "$devShortName" | tr '[:lower:]' '[:upper:]')"
+                                            echo "Device : ${CURR_DEV[devName]}, Board: ${CURR_BOARDS[brdName]}, ShortName:${alifDevShortName}." 
+                                            
+                                            if [[ "${CURR_DEV[devName]}" == "$alifDevShortName"* ]]; then
+                                                for osName in ${!CURR_OS[@]}
+                                                do
+                                                    echo "===================================================================================="
+                                                    if [ -d build ]; then
+                                                        echo -e "Deleting Build directory..."
+                                                        rm -rf build
+                                                    fi
+
+                                                    total_cfg_run_cnt=$((total_cfg_run_cnt + 1))
+                                                    echo "🚩 Building for ${CURR_COMPILER[comp]}, ${CURR_DEV[devName]}, ${CURR_OS[osName]}, ${CURR_BOOT[bootType]} ${CURR_RTSS[rtssType]} ${CURR_BOARDS[brdName]}"
+
+                                                    if [ "${CURR_DEV[devName]}" = "AE1C1F4051920" ] && [ "${CURR_RTSS[rtssType]}" = "HP" ]; then
+                                                        echo -e "🚨 ${CURR_DEV[devName]} does not have ${CURR_RTSS[rtssType]} subsystem"
+                                                        skipped_cfg_run_cnt=$((skipped_cfg_run_cnt + 1))
+                                                        continue
+                                                    fi
+
+                                                    actual_cfg_run_cnt=$((actual_cfg_run_cnt + 1))
+                                                    ./run.sh -p ${CURR_COMPILER[comp]},${CURR_COMPILER[comp]}_build,${CURR_COMPILER[comp]}_build_test -c --fresh -DBOOT=${CURR_BOOT[bootType]} -DDEVICE=${CURR_DEV[devName]} -DBOARD_NAME=${CURR_BOARDS[brdName]} -DOS=${CURR_OS[osName]} -DRTSS=${CURR_RTSS[rtssType]} -b --clean-first
+
+                                                    tmp=$?
+                                                    total_cmakeError=$((total_cmakeError + tmp))
+                                                    echo -e "🚫Error Status total_cmakeError: $total_cmakeError and tmp: $tmp"
+                                                    if [ "$tmp" -ne 0 ] ; then
+                                                        fail_cfg_run_cnt=$((fail_cfg_run_cnt + 1))
+                                                    fi
+                                                    echo "===================================================================================="
+                                                done
                                             fi
-
-                                            total_cfg_run_cnt=$((total_cfg_run_cnt + 1))
-                                            echo "🚩 Building for ${CURR_COMPILER[comp]}, ${CURR_DEV[devName]}, ${CURR_OS[osName]}, ${CURR_BOOT[bootType]}  ${CURR_RTSS[rtssType]}"
-
-                                            if [ "${CURR_DEV[devName]}" = "AE1C1F4051920" ] && [ "${CURR_RTSS[rtssType]}" = "HP" ]; then
-                                                echo -e "🚨 ${CURR_DEV[devName]} does not have ${CURR_RTSS[rtssType]} subsystem"
-                                                skipped_cfg_run_cnt=$((skipped_cfg_run_cnt + 1))
-                                                continue
-                                            fi
-
-                                            actual_cfg_run_cnt=$((actual_cfg_run_cnt + 1))
-                                            ./run.sh -p ${CURR_COMPILER[comp]},${CURR_COMPILER[comp]}_build,${CURR_COMPILER[comp]}_build_test -c --fresh -DBOOT=${CURR_BOOT[bootType]} -DDEVICE=${CURR_DEV[devName]} -DOS=${CURR_OS[osName]} -DRTSS=${CURR_RTSS[rtssType]} -b --clean-first
-
-                                            tmp=$?
-                                            total_cmakeError=$((total_cmakeError + tmp))
-                                            echo -e "🚫Error Status total_cmakeError: $total_cmakeError and tmp: $tmp"
-                                            if [ "$tmp" -ne 0 ] ; then
-                                                fail_cfg_run_cnt=$((fail_cfg_run_cnt + 1))
-                                            fi
-                                            echo "===================================================================================="
                                         done
                                     done
                                 done
