scripts: added build support in jenkin when DMA and blocking mode enable
compilation support added in jenkins for DMA and blocking mode enable

Signed-off-by: Raj Ranjan <raj.ranjan@alifsemi.com>

diff --git a/scripts/github/jenkins/Jenkinsfile b/scripts/github/jenkins/Jenkinsfile
--- a/scripts/github/jenkins/Jenkinsfile
+++ b/scripts/github/jenkins/Jenkinsfile
@@ -37,6 +37,12 @@ def buildDevice(deviceList) {
                         parallel_dis_run_cnt=0
                         parallel_dis_fail_cnt=0
                         parallel_dis_success_cnt=0
+                        dma_enable_run_cnt=0
+                        dma_enable_fail_cnt=0
+                        dma_enable_success_cnt=0
+                        blocking_mode_run_cnt=0
+                        blocking_mode_fail_cnt=0
+                        blocking_mode_success_cnt=0
                         retargeting_status=-1
 
                         CURR_OS=("NONE")
@@ -126,6 +132,37 @@ def buildDevice(deviceList) {
                                                 fi
                                                 total_cmakeError=\$((total_cmakeError + tmp))
 
+                                                #DMA Enable
+                                                dma_enable_run_cnt=\$((dma_enable_run_cnt + 1))
+                                                echo "🚩 Building for \${CURR_COMPILER[comp]}, ${currentDev}, \${CURR_OS[osName]}, \${CURR_BOOT[bootType]} \${CURR_RTSS[rtssType]} \${CURR_BOARDS[brdName]}, demo_parallel_display"
+
+                                                ./run.sh -f -c -DCFG_DMA_ENABLE=ON --fresh -DBOOT=\${CURR_BOOT[bootType]} -DDEVICE=${currentDev} -DBOARD_NAME=\${CURR_BOARDS[brdName]} -DOS=\${CURR_OS[osName]} -DRTSS=\${CURR_RTSS[rtssType]} -b --clean-first
+
+                                                tmp=\$?
+                                                if [ "\$tmp" -ne 0 ] ; then
+                                                    dma_enable_fail_cnt=\$((dma_enable_fail_cnt + 1))
+                                                else
+                                                    dma_enable_success_cnt=\$((dma_enable_success_cnt + 1))
+                                                fi
+                                                total_cmakeError=\$((total_cmakeError + tmp))
+                                                git status
+                                                git reset --hard
+
+                                                #Blocking Mode Enable
+                                                blocking_mode_run_cnt=\$((blocking_mode_run_cnt + 1))
+                                                echo "🚩 Building for \${CURR_COMPILER[comp]}, ${currentDev}, \${CURR_OS[osName]}, \${CURR_BOOT[bootType]} \${CURR_RTSS[rtssType]} \${CURR_BOARDS[brdName]}, demo_parallel_display"
+
+                                                ./run.sh -f -c -DCFG_DMA_ENABLE=ON --fresh -DBOOT=\${CURR_BOOT[bootType]} -DDEVICE=${currentDev} -DBOARD_NAME=\${CURR_BOARDS[brdName]} -DOS=\${CURR_OS[osName]} -DRTSS=\${CURR_RTSS[rtssType]} -b --clean-first
+
+                                                tmp=\$?
+                                                if [ "\$tmp" -ne 0 ] ; then
+                                                    blocking_mode_fail_cnt=\$((blocking_mode_fail_cnt + 1))
+                                                else
+                                                    blocking_mode_success_cnt=\$((blocking_mode_success_cnt + 1))
+                                                fi
+                                                total_cmakeError=\$((total_cmakeError + tmp))
+                                                git status
+                                                git reset --hard
                                                 echo "=================================================================================="
                                             done
                                         fi
@@ -147,16 +184,18 @@ def buildDevice(deviceList) {
                         echo -e " 🏆Success   : \$((actual_cfg_run_cnt - fail_cfg_run_cnt)), Failed: \$fail_cfg_run_cnt, Skipped: \$skipped_cfg_run_cnt"
                         echo -e " 🏆CDC       : success \$cdc200_success_cnt/\$cdc200_run_cnt, Failed: \$cdc200_fail_cnt/\$cdc200_run_cnt"
                         echo -e " 🏆Retarting : \$retargeting_status"
-                        echo -e " 🏆Parallel_Display : success \$parallel_dis_success_cnt/\$parallel_dis_run_cnt, Failed: \$parallel_dis_fail_cnt/\$parallel_dis_run_cnt"
+                        echo -e " 🏆DMA Enable: success \$dma_enable_success_cnt/\$dma_enable_run_cnt, Failed: \$dma_enable_fail_cnt/\$dma_enable_run_cnt"
+                        echo -e " 🏆Blocking Mode    : success \$parallel_dis_success_cnt/\$parallel_dis_run_cnt, Failed: \$parallel_dis_fail_cnt/\$parallel_dis_run_cnt"
+                        echo -e " 🏆Parallel_Display : success \$blocking_mode_success_cnt/\$blocking_mode_run_cnt, Failed: \$blocking_mode_fail_cnt/\$blocking_mode_run_cnt"
                         echo -e " 🔥Total Run => (\$actual_cfg_run_cnt/\$total_cfg_run_cnt)"
                         collective_total_Error=\$((total_cmakeError))
                         exit \$collective_total_Error
                     """
-				}
-			}
-		}
-	}
-	return stagesMap
+                }
+            }
+        }
+    }
+    return stagesMap
 }
 
 pipeline {
