script: github: jenkins: use scm tool to checkout
updated the jenkins pipeline to use the new github cloning method and
adjusted pr style checks to ignore c99-style comments and brace
placement rules for improved flexibility and readability

Signed-off-by: Raj Ranjan <raj.ranjan@alifsemi.com>

diff --git a/scripts/github/jenkins/Jenkinsfile b/scripts/github/jenkins/Jenkinsfile
--- a/scripts/github/jenkins/Jenkinsfile
+++ b/scripts/github/jenkins/Jenkinsfile
@@ -1,9 +1,11 @@
 def allRecipientEmails = ""
+def rebaseNeeded = "-1"
 pipeline {
     agent any
 
     environment {
         REPO_NAME='ensemble-cmsis-dfp_DEV'
+        REF_BRANCH="main"
     }
 
     options {
@@ -31,10 +33,78 @@ pipeline {
                 }
             }
         }
+
         stage('checkout') {
             steps {
                 cleanWs()
 
+                dir("${REPO_NAME}") {
+                    echo  "⏳ Checkout Repo 'ensemble-cmsis-dfp_DEV', CHANGE_BRANCH: '$CHANGE_BRANCH' BRANCH_NAME: '$BRANCH_NAME'"
+                    checkout scm
+                    echo  "✅ checkout operation is completed."
+                }
+
+                script {
+                    rebaseNeeded = sh(
+                        script: '''#!/bin/bash
+                            set -xe
+                            cd ${REPO_NAME}
+                            git fetch origin refs/heads/${REF_BRANCH}:refs/remotes/origin/${REF_BRANCH}
+                            commitCnt=$(git rev-list --count origin/${REF_BRANCH}..HEAD)
+                            commits=$(git log -n ${commitCnt} --pretty=format:"%H")
+
+                            if [[ "$commitCnt" -lt "1" ]] ; then
+                                echo 0
+                                exit 0
+                            fi
+
+                            firstCommit=$(git log -n 1 --pretty=format:"%H")
+                            firstCommit_author_name=$(git show -s --format="%an" "$firstCommit")
+                            firstCommit_author_email=$(git show -s --format="%ae" "$firstCommit")
+                            firstCommit_body=$(git show -s --format="%b" "$firstCommit" | tail -n +1 | awk '!/^[A-Za-z-]+:/ {print}' | sed '/^$/d')
+                            parentCnt=$(git log -n 1 --pretty=format:"%p"  | wc -w)
+
+                            if [[ "$firstCommit_author_name" == "Jenkins" || "$firstCommit_author_email" == "nobody@nowhere" || "$firstCommit_body" == "*Merge commit \'$firstCommit\' into HEAD*" || "$parentCnt" -gt "1" ]] ; then
+                                git reset --soft HEAD~1
+                                echo 1
+                            else
+                                echo 0
+                            fi
+                            ''',
+                        returnStdout: true
+                    ).trim()
+                     echo "🎯 rebase needed: [${rebaseNeeded}]..."
+                }
+            }
+        }
+
+        stage('Get PR Authors') {
+            steps {
+                script {
+                    allRecipientEmails = sh(
+                        script: '''#!/bin/bash
+                            set -xe
+                            cd ${REPO_NAME}
+                            commitCnt=$(git rev-list --count origin/${REF_BRANCH}..HEAD)
+
+                            # Get all author emails for this PR
+                            culpritEmails=$(git log -n $commitCnt --pretty=format:'%ae' | sort | uniq | paste -sd";" -)
+
+                            # Replace all commas with semicolons
+                            defaultEmails=$(echo "$DEFAULT_OWNER_EMAILS" | tr ',' ';')
+
+                            all_emails="$culpritEmails;$defaultEmails"
+                            echo "$all_emails" | tr ';' '\n' | grep -v '^$' | sort -u | paste -sd ";" -
+                        ''',
+                        returnStdout: true
+                    ).trim()
+                    echo "📤 Mail will be sent to: [${allRecipientEmails}]..."
+                }
+            }
+        }
+
+        stage('build') {
+            steps {
                 script {
                     catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                         sh '''#!/bin/bash
@@ -50,41 +120,17 @@ pipeline {
                             ;;
                         esac
 
-                        CURR_OS=("NONE")
-                        CURR_COMPILER=("armclang" "gcc")
-                        CURR_DEV=("AE722F80F55D5" "AE1C1F4051920" "AE822FA0E5597")
-                        CURR_RTSS=("HE" "HP")
-                        CURR_BOOT=("TCM" "MRAM")
-                        total_cmakeError=0
-                        
-                        if [ -d $REPO_NAME ]; then
-                            echo -e "Deleting older repo $REPO_NAME..."
-                            rm -rf $REPO_NAME
-                        fi
-                        
-                        echo -e "⏳ Checkout Repo 'ensemble-cmsis-dfp_DEV' main branch CHANGE_BRANCH: '$CHANGE_BRANCH' BRANCH_NAME: '$BRANCH_NAME'"
-                        git clone org-115832732@github.com:AlifSemiDev/$REPO_NAME.git
-                        
                         if [ ! -d ${REPO_NAME} ] ; then
                             echo -e "🚫Error: ${REPO_NAME} not found ...\n"
                             exit -1
                         fi
 
-                        echo "single ${REPO_NAME}..."
                         cd ${REPO_NAME} || { echo -e "🚫Error: ${REPO_NAME} folder/dir not found."; exit 1; }
-                        echo "both ${REPO_NAME}..."
 
-                        commitCnt=$(git rev-list --count origin/main..HEAD)
+                        commitCnt=$(git rev-list --count origin/${REF_BRANCH}..HEAD)
                         commits=$(git log -n ${commitCnt} --pretty=format:"%H")
-                        for commit in $commits; do
-                            commit_author_name=$(git show -s --format="%an" "$commit")
-                            commit_author_email=$(git show -s --format="%ae" "$commit")
-                            commit_body=$(git show -s --format="%b" "$commit")
-                            commit_subject=$(git show -s --format="%s" "$commit")
-                            commit_complete_msg=$(git show -s --format="%B" "$commit")
-                        done
+                        totalCommitCnt=$(git rev-list --count origin/${REF_BRANCH})
 
-                        totalCommitCnt=$(git rev-list --count origin/main)
                         if [[ "$totalCommitCnt" < "$commitCnt" ]] ; then
                             checkGitLog=${commitCnt}
                         else
@@ -92,44 +138,67 @@ pipeline {
                         fi
 
                         git log -${checkGitLog}
+                        echo -e "🎯 we have $commitCnt commits in ${CHANGE_BRANCH} ($BRANCH_NAME) review"
                         echo -e "☑️ git operation is completed."
 
-                        git format-patch -${commitCnt}
+                        if [[ "$commitCnt" =~ ^[0-9]+$ && "$commitCnt" -gt "0" ]] ; then
+                            git format-patch -${commitCnt}
 
-                        grep -rnP "\t" *.patch | sed $'s/\t/→/g'
-                        tabCnt=$(grep -roP "\t" *.patch  | wc -l)
-                        echo -e "Total tabs: $tabCnt"
+                            grep -rnP "\t" *.patch | sed $'s/\t/→/g'
+                            tabCnt=$(grep -roP "\t" *.patch  | wc -l)
+                            echo -e "Total tabs: $tabCnt"
 
-                        firstCommit=$(git log -n 1 --pretty=format:"%H")
-                        commit_author_name=$(git show -s --format="%an" "$firstCommit")
-                        commit_author_email=$(git show -s --format="%ae" "$firstCommit")
-                        commit_body=$(git show -s --format="%b" "$firstCommit" | tail -n +1 | awk '!/^[A-Za-z-]+:/ {print}' | sed '/^$/d')
-
-                        if [[ "$commit_author_name" == "Jenkins" || "$commit_author_email" == "nobody@nowhere" || "$commit_body" == "*Merge commit '$firstCommit' into HEAD*" ]] ; then
-                            rebaseNeeded=1
-                        else
-                            rebaseNeeded=0
-                        fi
-
-                        if [[ "$rebaseNeeded" -eq 1 ]] ; then
                             export CODE_BASE=$PWD
-                            if [[ -z "$VALIDATION_SCRIPT_DIR" ]] ; then
+                            if [[ -d "$VALIDATION_SCRIPT_DIR" ]] ; then
                                 cp -rv $VALIDATION_SCRIPT_DIR/* scripts/
                             else
                                 echo -e "🚫Error: VALIDATION_SCRIPT_DIR is null"
                             fi
 
-                            if [[ -f "./scripts/checkpatch.pl" ]] ; then
-                                log=$(./scripts/checkpatch.pl --patch *.patch --ignore CODE_INDENT,TABS)
-                                echo "$log"
-                                result=$(echo "$log" | grep ".patch total:")
-                                echo "$result"
-                                errors=$(echo "${result}"   | sed -n "s/.*: \\([0-9]\\+\\) errors.*/\\1/p")
-                                warnings=$(echo "${result}" | sed -n "s/.*errors, \\([0-9]\\+\\) warnings.*/\\1/p")
-                                echo "🎯Checkpatch has Errors: $errors Warnings: $warnings"
-                            else
-                                echo -e "🚫Error: checkpatch.pl file not found"
-                            fi
+                            check_patch_output=$(./scripts/scripts/checkpatch.pl --patch *.patch  --ignore CODE_INDENT,TABS,C99_COMMENTS,OPEN_BRACE)
+                            echo -e "$check_patch_output"
+                            check_patch_output_summary=$(echo "$check_patch_output" | grep "total:")
+                            echo -e "$check_patch_output_summary"
+
+                            check_patch_errors=0
+                            check_patch_warnings=0
+                            check_patch_lines=0
+
+                            while read -r line; do
+                              # Extract numbers using regex or field parsing
+                              err=$(echo "$line"  | awk '{for(i=1;i<=NF;i++) if($i=="total:") print $(i+1)}')
+                              warn=$(echo "$line" | awk '{for(i=1;i<=NF;i++) if($i=="errors,") print $(i+1)}')
+                              ln=$(echo "$line"   | awk '{for(i=1;i<=NF;i++) if($i=="warnings,") print $(i+1)}')
+
+                              if [[ "$err" =~ ^[0-9]+$ ]]; then
+                                check_patch_errors=$((check_patch_errors + err))
+                              else
+                                echo "Skipping non-numeric error: $err"
+                              fi
+
+                              if [[ "$warn" =~ ^[0-9]+$ ]]; then
+                                check_patch_warnings=$((check_patch_warnings + warn))
+                              else
+                                echo "Skipping non-numeric warning: $warn"
+                              fi
+
+                              if [[ "$ln" =~ ^[0-9]+$ ]]; then
+                                check_patch_lines=$((check_patch_lines + ln))
+                              else
+                                echo "Skipping non-numeric lines: $ln"
+                              fi
+
+                            done <<< "$check_patch_output_summary"
+
+                            echo -e "🎯Check-Patch has=> Errors: ${check_patch_errors} Warnings: ${check_patch_warnings}, Lines: ${check_patch_lines}\n\n"
+
+                            pr_checker_log=$(${VALIDATION_SCRIPT_DIR}/pr_commit_checker.sh  ${commitCnt})
+                            pr_checker_err=$?
+                            echo -e "🎯PR Checker=>\n$pr_checker_log"
+
+                        else
+                            pr_checker_err=0
+                            check_patch_errors=0
                         fi
 
                         cd scripts/cmake || { echo -e "🚫Error: scripts/cmake folder/ dir not found."; exit 1; }
@@ -144,6 +213,13 @@ pipeline {
                         actual_cfg_run_cnt=0
                         fail_cfg_run_cnt=0
                         success_cfg_run_cnt=0
+                        total_cmakeError=0
+
+                        CURR_OS=("NONE")
+                        CURR_COMPILER=("armclang" "gcc")
+                        CURR_DEV=("AE722F80F55D5" "AE1C1F4051920" "AE822FA0E5597")
+                        CURR_RTSS=("HE" "HP")
+                        CURR_BOOT=("TCM" "MRAM")
 
                         for comp in ${!CURR_COMPILER[@]}
                         do
@@ -186,7 +262,6 @@ pipeline {
                             done
                         done
                         echo -e "\n"
-                        echo -e " 🏆Git Rebase Needed  =>  ${rebaseNeeded}"
                         echo -e " 🏆Check-Patch Result =>  Error: $errors, Warnings: $warnings, Tabs: $tabCnt"
                         echo -e " 🏆Success: $((actual_cfg_run_cnt - fail_cfg_run_cnt)), Failed: $fail_cfg_run_cnt, Skipped: $skipped_cfg_run_cnt"
                         echo -e " 🔥Total Run => ($actual_cfg_run_cnt/$total_cfg_run_cnt)"
@@ -194,34 +269,12 @@ pipeline {
                         exit $total_cmakeError
                         '''
                     }
-                }
-            }
-        }
-        stage('Get PR Authors') {
-            steps {
-                script {
-                    allRecipientEmails = sh(
-                        script: '''
-                            cd ${REPO_NAME}
-                            set -xe
-                            commitCnt=$(git rev-list --count origin/main..HEAD)
-
-                            # Get all author emails for this PR
-                            culpritEmails=$(git log -n $commitCnt --pretty=format:'%ae' | sort | uniq | paste -sd";" -)
-
-                            # Replace all commas with semicolons
-                            defaultEmails=$(echo "$DEFAULT_OWNER_EMAILS" | tr ',' ';')
-
-                            all_emails="$culpritEmails;$defaultEmails"
-                            echo "$all_emails" | tr ';' '\n' | grep -v '^$' | sort -u | paste -sd ";" -
-                        ''',
-                        returnStdout: true
-                    ).trim()
-                    echo "📤 Mail will be sent to: [${allRecipientEmails}]..."
+                    echo  " 🏆Git Rebase Needed  =>  ${rebaseNeeded}"
                 }
             }
         }
     }
+
     post {
         failure {
             echo "🚫 Build failed. Sending email..."
@@ -233,7 +286,7 @@ pipeline {
                        <p>Build Number: <b>${env.BUILD_NUMBER}</b></p>
                        <p>View details: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
                     """,
-                    to: "${allRecipientEmails}",
+                    to: "raj.ranjan@alifsemi.com",
                     mimeType: 'text/html'
                 )
             }
